cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/cask-drivers"

brew "curl"
brew "git"
brew "shellcheck"
brew "tree"
brew "watch"
brew "wget"
brew "colordiff"
brew "awscli"
brew "mkcert"
brew "libpq"
brew "hadolint"
brew "goodwithtech/r/dockle"
brew "aquasecurity/trivy/trivy"
brew "peco"
brew "mas"
brew "graphviz"
brew "nvm"
brew "kayac/tap/ecspresso"
brew "fujiwara/tap/tracer"
brew "jq"
brew "pre-commit"
brew "aquaproj/aqua/aqua"
brew "volta"

cask "alfred"
cask "docker"
cask "google-japanese-ime"
cask "iterm2"
cask "visual-studio-code"
cask "zoom"
cask "postman"
cask "karabiner-elements"
cask "1password"
cask "tableplus"
cask "adoptopenjdk"
cask "google-chrome"
cask "notion"

mas "Flow - Focus & Pomodoro Timer", id:1423210932
mas "LINE", id:539883307
mas "Yoink", id:457622435
mas "Mail for Gmail", id:1216244845
